spring:
  application:
    name: spring-project
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 40MB

file:
  upload:
    path: ./uploads

server:
  tomcat:
    max-swallow-size: 40MB

app:
  cors:
    allowed-origins: http://localhost:5173
